version: "2"
services:
    app:
        container_name: "app"
        restart: always
        build: .
        environment:
            - MONGO_URI=mongodb://mongo/magicCard
            - PORT=3000
            - NODE_ENV=production
        ports:
            - "3000:3000"
        links:
            - mongo
        depends_on:
            - mongo
        command: npm start

    app-dev:
        container_name: "app-dev"
        restart: always
        build: .
        environment:
            - MONGO_URI=mongodb://mongo/magicCard
            - PORT=3001
            - NODE_ENV=developer
        ports:
            - "3001:3001"
            - "5555:5555"
        links:
            - mongo
        depends_on:
            - mongo
        command: npm run dev
        volumes:
            - ./:/usr/src/app 

    mongo:
        container_name: "mongo"
        image: mongo
        ports:
            - "27017:27017"
        # command: mongod --smallfiles --logpath=/dev/null # --quiet